name: Build

on:
  push:
    tags:
      - 'v*'
jobs:
  # createrelease:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   outputs:
  #     release_url: ${{ steps.create-release.outputs.upload_url }}
  #   steps:
  #   - name: Create Release
  #     id: create-release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: Release ${{ github.ref }}
  #       draft: false
  #       prerelease: false
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          TARGET: linux
          CMD_BUILD: >
              echo "build" >> "build"
              zip -9 audible_linux_ubuntu_latest build
          OUT_FILE_NAME: audible_linux_ubuntu_latest.zip
        - os: ubuntu-20.04
          TARGET: linux
          CMD_BUILD: >
              echo "build" >> "build"
              zip -9 audible_linux_ubuntu_20_04 build
          OUT_FILE_NAME: audible_linux_ubuntu_20_04.zip
     
    steps:
    - name: Build for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{matrix.OUT_FILE_NAME}}
