name: Release-2

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # write required for action-gh-release
      id-token: write
    steps:
    - name: Build-Artifact-2
      run: |
        echo "building artifact"
        echo "artifact2" >> "artifact2"
    - name: Release-Artifact-2
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifact2
