name: Release-1

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # write required for action-gh-release
      id-token: write
    steps:
    - name: Build-Artifact-1
      run: |
        echo "building artifact"
        echo "artifact1" >> artifact1
    - name: Release-Artifact-1
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifact1
